# k8s/external-secret.yaml (수정 완료 버전)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dang-dang-spring-db-creds-es
  namespace: dang-dang-spring-ns
spec:
  refreshInterval: "1h" # 동기화 주기
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: my-app-db-secret
  dataFrom:
    - extract:
        key: doong